services:
  ehrdb:
    image: postgres:14
    container_name: ehrdb
    environment:
      POSTGRES_USER: ehrbase
      POSTGRES_PASSWORD: ehrbase
      POSTGRES_DB: ehrbase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  ehrbase:
    image: ehrbase/ehrbase:latest
    container_name: ehrbase
    depends_on:
      - ehrdb
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHADMINUSER: ehrbase-admin
      SECURITY_AUTHADMINPASSWORD: SuperSecretAdminPassword
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: ehrbase-user
      SECURITY_AUTHPASSWORD: SuperSecretPassword
      ADMIN_API_ACTIVE: "true"
      CORS_ENABLED: "true"
    ports:
      - "8080:8080"
volumes:
  db-data: